---
k: 100
retriever: svs
query_file: nq_eval.json
query_dataset: nq
doc_dataset: kilt_wikipedia
output_file: None
embed_file: kilt-wp-bge1.5-base.fvecs
embed_model_name: BAAI/bge-base-en-v1.5
embed_model_type: 'st'
index_fn: pysvs.Flat
dist_type: pysvs.DistanceType.MIP
index_kwargs: 